DELETE http://localhost:3000/subscribers

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "John Doe",
    "subscribedToChannel": "Mosh"
}

###
POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Mary Doe",
    "subscribedToChannel": "Mosh"
}
###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "JimBob Anna",
    "subscribedToChannel": "MoshPit"
}
###

GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/6583420ecc14d2739b40ccd3


###
DELETE http://localhost:3000/subscribers/6583420ecc14d2739b40ccd3

###
PATCH http://localhost:3000/subscribers/65834232cc14d2739b40ccdd
Content-Type: application/json

{
    "name": "JimBob AnnaPatch"
}
###

PUT http://localhost:3000/subscribers/6583420fcc14d2739b40ccd5
Content-Type: application/json

{
    "name": "JimBob Anna",
    "subscribedToChannel": "MoshPitPut"
}


